// <auto-generated />
using System;
using BankSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankSystem.Migrations
{
    [DbContext(typeof(ClientsDbContext))]
    partial class ClientsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BankSystem.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_lastChangeBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_lastChangeData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_lastChangeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("_lastChangeTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
